name: Build Succeeds on PR

on:
  pull_request:
  branches:
    - master
    - main

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
      - uses: actions/setup@v3
        with:
        node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Genrate  prisma client
      - run: npx prisma generate

      - name: Build the project
        run: cd packages/db && npx prisma generate

      - name: Run Build
        run: npm run build
