name: Build and Deploy to Docker Hub and EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tags: imkuldeepahlawat/week-18-class:${{ github.sha }}

      - name: Verify Pushed Image
        run: docker pull imkuldeepahlawat/week-18-class:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          debug: true
          script: |
            echo "Connection successful"
            # Pull the new image
            sudo docker pull imkuldeepahlawat/week-18-class:${{ github.sha }}

            # Stop and remove the old container
            sudo docker stop web-app || true
            sudo docker rm web-app || true

            # Run the new container
            sudo docker run -d \
              --name web-app \
              --restart unless-stopped \
              -p 3005:3000 \
              -e NODE_ENV=production \
              imkuldeepahlawat/week-18-class:${{ github.sha }}

            # Clean up old images
            sudo docker image prune -af

            echo "Deployment completed successfully"
